### ISSUE TITLE
Resources to Document

### ISSUE THREAD

**Issue by thomasplevy** [gocodebox/lifterlms-rest#1]
## Phase 1 (Completed)

Resources to be made available in the first phase of the API. Target public release August 2019.

- [x] Student accounts `/students`
- [x] Student enrollments `/students/{id}/enrollments`
- [x] Student Progress `/students/{id}/progress`
- [x] Instructors `/instructors`
- [x] Instructor Content `/instructors/{id}/content`
- [x] Courses `/courses`
- [x] Course Enrollments `/courses/{id}/enrollments`
- [x] Course Instructors ~`/courses/{id}/instructors`~ `/instructors?post={id}`
- [x] Course Contents (syllabus/outline) `/courses/{id}/contents`
- [x] Sections `/sections`
- [x] Lessons `/lessons`
- [ ] Quizzes `/quizzes`
- [ ] Quiz Questions `/questions`
- [x] Enrollments `/enrollments`
- [x] Memberships `/memberships`
- [x] Membership Enrollments ~`/memberships/{id}/enrollments`~ `/enrollments?post={id}`
- [x] Access Plans `/access-plans`
- [x] Webhooks

## Ecommerce

- [ ] Orders `/orders`
- [ ] Transactions `/orders/{id}/transactions`
- [ ] Refunds `/orders/{id}/refunds`
- [ ] Coupons `/coupons`

## Engagements

- [ ] Engagements
- [ ] Achievements
- [ ] Certificates
- [ ] engagement emails

## Grades & Quizzes

- [ ] Course Grades `/courses/{id}/grades`
- [ ] Quiz Attempts `/quizzes/{id}/attempts`

## System & Status

- [ ] Settings `/settings`
- [ ] Integrations
- [ ] Payment Gateways
- [ ] System Status
- [ ] Reports (sales, enrollments, etc...)

## Other

- [ ] Reviews `/reviews/` [#10]
- [ ] Vouchers `/vouchers`
- [ ] Notifications `/notifications`
- [ ] Events `/events` - See https://github.com/gocodebox/lifterlms/issues/636

### Assignments
- [ ] Assignments `/assignments`
- [ ] Assignment Tasks `/assignments/{id}/tasks`
- [ ] Assignment Submissions `/assignments/{id}/submissions`

### Social Learning

(todo)

### Private Areas

- [ ] Private posts `/private-posts` (CRUD)
- [ ] Private Post Comments `/private-posts/{id}/comments` (possibly unnecessary due to commenting api available via the WP core).
- [ ] Automations `/private-post-automations/` (CRUD) 

### Advanced Quizzes

+ [ ] Additional question types
